!'f' watched
! Evaluate: f(4);
! Evaluate: f(3);
! Evaluate: f(2);
! Evaluate: f(1);
! Evaluate: f(0);
! Yields: 1;
! f returns: 1;
! f returns: 2;
! f returns: 6;
! f returns: 24;
24;
! f := {!Set!};
! f(3) := 4;
! f(4) := 5;
{[3, 4], [4, 5]};
!'f' unwatched
!'f' watched
! Evaluate: f(6);
! Evaluate: f(5);
! Evaluate: f(4);
! Evaluate: f(3);
! Evaluate: f(2);
! Yields: 1;
! Evaluate: f(1);
! Yields: 1;
! f(3) := 2;
! Evaluate: f(3);
! Yields: 2;
! f returns: 2;
! Evaluate: f(2);
! Yields: 1;
! f(4) := 3;
! Evaluate: f(4);
! Yields: 3;
! f returns: 3;
! Evaluate: f(3);
! Yields: 2;
! f(5) := 5;
! Evaluate: f(5);
! Yields: 5;
! f returns: 5;
! Evaluate: f(4);
! Yields: 3;
! f(6) := 8;
! Evaluate: f(6);
! Yields: 8;
! f returns: 8;
8;
! Evaluate: f(7);
! Evaluate: f(6);
! Yields: 8;
! Evaluate: f(5);
! Yields: 5;
! f(7) := 13;
! Evaluate: f(7);
! Yields: 13;
! f returns: 13;
13;
!'f' unwatched

