/*
 * Note:	The header line below is parsed by interpreter.c for the
 * version, date, and time of the last update; altering this field from
 * the standard format generated by RCS will yield unpredictable (and
 * undesireable) results.		ahd@clutx, 21Feb87
 */

char    rev_info[] = "Author: Gary Levin\n\
Developed at Clarkson University\n\
Copyright Gary Levin 1986, 1987, 1988, 1989, 1990\n\
$Header: rev_info.c,v 1.19 90/07/05 11:00:00 gary Locked $\n";
